fix: add animate property to NSWindow:setFrame:
servo/core-foundation-rs pull request #516
Opened 2022-06-27 05:11 UTC by keiya01

I added animate property to `NSWindow:setFrame:`.
If this behavior is intended, I'm sorry but please close this PR.

2022-06-27 18:49 UTC, madsmtm requested changes
[`-[NSWindow setFrame:display:]`](https://developer.apple.com/documentation/appkit/nswindow/1419753-setframe?language=objc) and [`-[NSWindow setFrame:display:animate:]`](https://developer.apple.com/documentation/appkit/nswindow/1419519-setframe?language=objc) are different methods, so I think you should add `setFrame_display_animate_` instead of changing the existing `setFrame_display_`.

2022-06-27 23:59 UTC, keiya01 commented
> [`-[NSWindow setFrame:display:]`](https://developer.apple.com/documentation/appkit/nswindow/1419753-setframe?language=objc) and [`-[NSWindow setFrame:display:animate:]`](https://developer.apple.com/documentation/appkit/nswindow/1419519-setframe?language=objc) are different methods, so I think you should add `setFrame_display_animate_` instead of changing the existing `setFrame_display_`.

I see. I fixed your review.

2022-08-15 12:11 UTC, bors-servo commented
:pushpin: Commit 0df00e0 has been approved by `jdm`

<!-- @bors-servo r=jdm 0df00e0543b19a6b3b598793bdeb97fee699bd21 -->

2022-08-15 12:11 UTC, bors-servo commented
:hourglass: Testing commit 0df00e0543b19a6b3b598793bdeb97fee699bd21 with merge b4f9fcf836b74d9644691bc252ae84a09a3d1cb4...

2022-08-15 22:11 UTC, bors-servo commented
:boom: Test timed out

2022-08-17 01:39 UTC, jdm commented
@bors-servo retry

2022-08-17 01:43 UTC, bors-servo commented
:hourglass: Testing commit 0df00e0543b19a6b3b598793bdeb97fee699bd21 with merge bb8852eff82a148248e1bcdeedb8a7efdeb6985e...

2022-08-17 01:45 UTC, bors-servo commented
:sunny: Test successful - [checks-github](https://github.com/servo/core-foundation-rs/runs/7870246467?check_suite_focus=true)
Approved by: jdm
Pushing bb8852eff82a148248e1bcdeedb8a7efdeb6985e to master...

2022-08-17 01:45 UTC, merged